// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types'
import course from './course'
import altitude from './altitude'
import water from './water'
import roads from './roads'
import objects from './objects'
import buildings from './buildings'
import paths from './paths'
import regions from './regions'
import trees from './trees'

const level: LevelData = {
	id: 'lillsjon',
	name: 'Lillsjon',
	course,
	altitude,
	water,
	roads,
	objects,
	buildings,
	paths,
	regions,
	manualTrees: trees,
	hide: true,
}

export default level
