// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types';
import course from './course.json';
import altitude from './altitude.json';
import water from './water.json';
import roads from './roads.json';
import objects from './objects.json';
import buildings from './buildings.json';
import paths from './paths.json';
import regions from './regions.json';
import trees from './trees.json';

const level: LevelData = {
  id: 'lillsjon',
  name: 'Lillsjon',
  course: course as LevelData['course'],
  altitude: altitude as LevelData['altitude'],
  water: water as LevelData['water'],
  roads: roads as LevelData['roads'],
  objects: objects as LevelData['objects'],
  buildings: buildings as LevelData['buildings'],
  paths: paths as LevelData['paths'],
  regions: regions as LevelData['regions'],
  manualTrees: trees as LevelData['manualTrees'],
  hide: true,
};

export default level;
