import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LEVELS_DIR = path.resolve(__dirname, 'apps/game/src/levels');

const levelIds = ['cheltenham', 'huddinge', 'judarskogen', 'lillsjon', 'uppsala'];

function writeJson(filePath: string, data: unknown) {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
}

for (const id of levelIds) {
  const srcPath = path.resolve(LEVELS_DIR, `${id}.map.ts`);
  if (!fs.existsSync(srcPath)) {
    console.warn(`⚠ Skipping ${id}: not found`);
    continue;
  }

  // Dynamic import of the TS module (tsx handles this)
  const mod = await import(srcPath);
  const data = mod.default;
  if (!data) {
    console.error(`❌ No default export for ${id}`);
    continue;
  }

  const dir = path.join(LEVELS_DIR, id);
  fs.mkdirSync(dir, { recursive: true });

  // Always write core files
  const cleanCourse = {
    eventId: data.course.eventId,
    coordinates: data.course.coordinates,
    points: data.course.points,
  };
  writeJson(path.join(dir, 'course.json'), cleanCourse);
  writeJson(path.join(dir, 'altitude.json'), data.altitude);
  writeJson(path.join(dir, 'water.json'), data.water);

  // Optional files
  const optionalMap: Record<string, unknown> = {};
  if (data.buildings?.length) optionalMap.buildings = data.buildings;
  if (data.paths?.length) optionalMap.paths = data.paths;
  if (data.marshals?.length) optionalMap.marshals = data.marshals;
  if (data.roads?.length) optionalMap.roads = data.roads;

  for (const [key, value] of Object.entries(optionalMap)) {
    writeJson(path.join(dir, `${key}.json`), value);
  }

  // Generate index.ts
  const imports: string[] = [
    `// Auto-generated by scripts/fetch-level.ts — do not edit manually`,
    `import type { LevelData } from '../types';`,
    `import course from './course.json';`,
    `import altitude from './altitude.json';`,
    `import water from './water.json';`,
  ];
  const fields: string[] = [
    `  id: '${data.id}',`,
    `  name: '${data.name}',`,
    `  course: course as LevelData['course'],`,
    `  altitude,`,
    `  water: water as LevelData['water'],`,
  ];

  if (optionalMap.buildings) {
    imports.push(`import buildings from './buildings.json';`);
    fields.push(`  buildings: buildings as LevelData['buildings'],`);
  }
  if (optionalMap.paths) {
    imports.push(`import paths from './paths.json';`);
    fields.push(`  paths: paths as LevelData['paths'],`);
  }
  if (optionalMap.marshals) {
    imports.push(`import marshals from './marshals.json';`);
    fields.push(`  marshals: marshals as LevelData['marshals'],`);
  }
  if (optionalMap.roads) {
    imports.push(`import roads from './roads.json';`);
    fields.push(`  roads: roads as LevelData['roads'],`);
  }
  if (data.hide !== undefined) {
    fields.push(`  hide: ${data.hide},`);
  }

  const indexContent = [
    ...imports,
    ``,
    `const level: LevelData = {`,
    ...fields,
    `};`,
    ``,
    `export default level;`,
    ``,
  ].join('\n');

  fs.writeFileSync(path.join(dir, 'index.ts'), indexContent, 'utf-8');

  // Report
  const allFiles = fs.readdirSync(dir);
  const sizes = allFiles.map(f => {
    const s = fs.statSync(path.join(dir, f));
    return `${f} (${(s.size / 1024).toFixed(1)}KB)`;
  });
  console.log(`✅ ${id}: ${sizes.join(', ')}`);
}

console.log('\nDone!');
