/**
 * The voiceover: the original, line for line, with the name swapped and
 * the club's own promises worked in. An empty string is a breath: the
 * announcer pauses a little longer.
 */
export const SCRIPT: string[] = [
	'Welcome to Scoop Bus',
	'This is Scoop Bus',
	'Welcome',
	'This is Scoop Bus',
	'Welcome to Scoop Bus',
	'',
	'You can do anything at Scoop Bus',
	'Anything at all',
	'The only limit is yourself',
	'The only limit is the finish funnel',
	'The bus will pick you up at Scoop Bus',
	'Nobody is left behind at Scoop Bus',
	'Car park attendant is possible at Scoop Bus',
	'The scoop is at the front of the bus at Scoop Bus',
	'Welcome to Scoop Bus',
	'',
	'This is Scoop Bus and welcome to you',
	'Yes, this is Scoop Bus',
	'Haga parkrun is possible at Scoop Bus',
	`Rick's Dad Tony is welcome at Scoop Bus`,
	'This is Scoop Bus, and welcome to you who has come to Scoop Bus',
	'',
	'Anything is possible at Scoop Bus',
	'You can do anything at Scoop Bus',
	'Fika is mandatory at Scoop Bus',
	'A kanelbulle is possible at Scoop Bus',
	'A second kanelbulle is possible at Scoop Bus',
	'The infinite is possible at Scoop Bus',
	'The unattainable is unknown at Scoop Bus',
	'Running as park walker is possible at Scoop Bus',
	'A personal best is possible, but not required, at Scoop Bus',
	'Snow is not an excuse at Scoop Bus',
	'',
	'Welcome to Scoop Bus',
	'This is Scoop Bus',
	'Parkrun is not a race at Scoop Bus',
	'Track and Food, on a Wednesday, at Scoop Bus',
	'Mostly food, at Scoop Bus',
	'Volunteering as car park attendant is possible at Scoop Bus',
	'Welcome to Scoop Bus',
	'Welcome',
	'This is Scoop Bus',
	'',
	'Welcome to Scoop Bus',
	'Bring your barcode to Scoop Bus',
	'ScoopCoin is not financial advice at Scoop Bus',
	'A Furby is possible at Scoop Bus',
	'The badgers are also here at Scoop Bus',
	'Your sticker has been made at Scoop Bus',
	'Welcome to Scoop Bus',
	'',
]
