/**
 * Auto-generated barrel file — re-generated by scripts/fetch-level.ts
 * Do not edit manually.
 */
import type { LevelData } from './types';

import cheltenham from './cheltenham.map';
import haga from './haga.map';
import huddinge from './huddinge.map';
import judarskogen from './judarskogen.map';
import lillsjon from './lillsjon.map';
import uppsala from './uppsala.map';

export type { LevelData } from './types';

const levels: Record<string, LevelData> = {
  cheltenham,
  haga,
  huddinge,
  judarskogen,
  lillsjon,
  uppsala,
};

export default levels;
