/**
 * Level registry — provides metadata eagerly & full data lazily.
 *
 * Auto-generated by scripts/fetch-level.ts
 */
import type { LevelData } from './types'
import hagaLevel from './haga/index'
import hagaImg from '../assets/levels/haga.png'
import huddingeImg from '../assets/levels/huddinge.png'
import judarskogenImg from '../assets/levels/judarskogen.png'
import kristinebergImg from '../assets/levels/kristineberg.png'
import lillsjonImg from '../assets/levels/lillsjon.png'
import cheltenhamImg from '../assets/levels/cheltenham.png'
import uppsalaImg from '../assets/levels/uppsala.png'

// ── Level metadata (always available, no heavy data) ─────────────────

export interface LevelMeta {
	id: string
	name: string
	hide?: boolean
	/** Display name when alt course is selected (shift+click) */
	altCourseName?: string
	/** Optional preview image URL for the level select grid */
	image?: string
}

const levelMeta: LevelMeta[] = [
	{ id: 'cheltenham', name: 'Cheltenham', hide: true, image: cheltenhamImg },
	{
		id: 'haga',
		name: 'Haga',
		altCourseName: 'Haga (alt course)',
		image: hagaImg,
	},
	{ id: 'huddinge', name: 'Huddinge', image: huddingeImg },
	{ id: 'judarskogen', name: 'Judarskogen', image: judarskogenImg },
	{ id: 'kristineberg', name: 'Kristineberg', image: kristinebergImg },
	{ id: 'lillsjon', name: 'Lillsjön', image: lillsjonImg },
	{ id: 'uppsala', name: 'Uppsala', hide: true, image: uppsalaImg },
]

export const levels: Record<string, LevelMeta> = Object.fromEntries(
	levelMeta.map((m) => [m.id, m]),
)

// ── Lazy loader — resolves the full LevelData on demand ──────────────

const loaders: Record<string, () => Promise<{ default: LevelData }>> = {
	cheltenham: () => import('./cheltenham/index'),
	haga: () => import('./haga/index'),
	huddinge: () => import('./huddinge/index'),
	judarskogen: () => import('./judarskogen/index'),
	kristineberg: () => import('./kristineberg/index'),
	lillsjon: () => import('./lillsjon/index'),
	uppsala: () => import('./uppsala/index'),
}

const cache = new Map<string, LevelData>([['haga', hagaLevel]])

export async function loadLevel(id: string): Promise<LevelData> {
	const cached = cache.get(id)
	if (cached) return cached

	const loader = loaders[id]
	if (!loader) {
		const available = Object.keys(loaders).join(', ')
		throw new Error(
			`Unknown level "${id}". Available levels: ${available || '(none — run pnpm game:level <id>)'}`,
		)
	}

	const mod = await loader()
	cache.set(id, mod.default)
	return mod.default
}

export type { LevelData } from './types'

// Default export for backward-compat: the metadata record
export default levels
