/**
 * Level registry — provides metadata eagerly & full data lazily.
 *
 * Auto-generated by scripts/fetch-level.ts
 */
import type { LevelData } from './types';
import hagaLevel from './haga/index';

// ── Level metadata (always available, no heavy data) ─────────────────

export interface LevelMeta {
  id: string;
  name: string;
  hide?: boolean;
  /** Display name when alt course is selected (shift+click) */
  altCourseName?: string;
}

const levelMeta: LevelMeta[] = [
  { id: 'cheltenham', name: 'Cheltenham', hide: true },
  { id: 'haga', name: 'Haga', altCourseName: 'Haga (alt course)' },
  { id: 'huddinge', name: 'Huddinge' },
  { id: 'judarskogen', name: 'Judarskogen' },
  { id: 'kristineberg', name: 'Kristineberg' },
  { id: 'lillsjon', name: 'Lillsjön', hide: true },
  { id: 'uppsala', name: 'Uppsala', hide: true },
];

export const levels: Record<string, LevelMeta> = Object.fromEntries(
  levelMeta.map((m) => [m.id, m]),
);

// ── Lazy loader — resolves the full LevelData on demand ──────────────

const loaders: Record<string, () => Promise<{ default: LevelData }>> = {
  cheltenham: () => import('./cheltenham/index'),
  haga: () => import('./haga/index'),
  huddinge: () => import('./huddinge/index'),
  judarskogen: () => import('./judarskogen/index'),
  kristineberg: () => import('./kristineberg/index'),
  lillsjon: () => import('./lillsjon/index'),
  uppsala: () => import('./uppsala/index'),
};

const cache = new Map<string, LevelData>([
  ['haga', hagaLevel],
]);

export async function loadLevel(id: string): Promise<LevelData> {
  const cached = cache.get(id);
  if (cached) return cached;

  const loader = loaders[id];
  if (!loader) {
    const available = Object.keys(loaders).join(', ');
    throw new Error(
      `Unknown level "${id}". Available levels: ${available || '(none — run pnpm game:level <id>)'}`,
    );
  }

  const mod = await loader();
  cache.set(id, mod.default);
  return mod.default;
}

export type { LevelData } from './types';

// Default export for backward-compat: the metadata record
export default levels;
