/**
 * Pre-extract raw RGBA pixel data from custom runner sprite PNGs.
 * Outputs a generated TypeScript file that can be imported synchronously at runtime.
 *
 * Usage: npx tsx apps/web/scripts/gen-custom-runner-pixels.ts
 * Runs automatically before dev/build via package.json scripts.
 */

import fs from 'node:fs'
import path from 'node:path'
import { PNG } from 'pngjs'

const CUSTOM_DIR = path.resolve(
	import.meta.dirname,
	'../src/assets/runners/custom',
)
const OUTPUT_FILE = path.resolve(CUSTOM_DIR, 'pixel-data.generated.ts')

interface SpriteData {
	name: string
	filename: string
}

const sprites: SpriteData[] = [
	{ name: 'run', filename: 'run.png' },
	{ name: 'sit', filename: 'sit.png' },
	{ name: 'head', filename: 'head.png' },
]

function extractPixelData(filePath: string): {
	width: number
	height: number
	base64: string
} {
	const buffer = fs.readFileSync(filePath)
	const png = PNG.sync.read(buffer)
	const base64 = Buffer.from(png.data).toString('base64')
	return { width: png.width, height: png.height, base64 }
}

const entries: string[] = []

for (const sprite of sprites) {
	const filePath = path.join(CUSTOM_DIR, sprite.filename)
	if (!fs.existsSync(filePath)) {
		console.warn(`⚠ Skipping ${sprite.filename} (not found)`)
		entries.push(
			`export const ${sprite.name}Pixels: SpritePixelData | null = null`,
		)
		continue
	}
	const { width, height, base64 } = extractPixelData(filePath)
	console.log(
		`✓ ${sprite.filename}: ${width}×${height} (${base64.length} bytes base64)`,
	)
	entries.push(
		`export const ${sprite.name}Pixels: SpritePixelData = { width: ${width}, height: ${height}, pixels: '${base64}' }`,
	)
}

const output = `// AUTO-GENERATED by scripts/gen-custom-runner-pixels.ts — do not edit manually

export interface SpritePixelData {
	width: number
	height: number
	/** Base64-encoded raw RGBA pixel buffer */
	pixels: string
}

${entries.join('\n\n')}
`

fs.writeFileSync(OUTPUT_FILE, output)
console.log(`\n✓ Written to ${path.relative(process.cwd(), OUTPUT_FILE)}`)
