// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types'
import course from './course'
import altitude from './altitude'
import water from './water'
import buildings from './buildings'
import paths from './paths'
import roads from './roads'
import objects from './objects'

const level: LevelData = {
	id: 'huddinge',
	name: 'Huddinge',
	course,
	altitude,
	water,
	buildings,
	paths,
	roads,
	objects,
}

export default level
