// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types';
import course from './course.json';
import altitude from './altitude.json';
import water from './water.json';
import buildings from './buildings.json';
import paths from './paths.json';
import roads from './roads.json';

const level: LevelData = {
  id: 'huddinge',
  name: 'Huddinge',
  course: course as LevelData['course'],
  altitude,
  water: water as LevelData['water'],
  buildings: buildings as LevelData['buildings'],
  paths: paths as LevelData['paths'],
  roads: roads as LevelData['roads'],
};

export default level;
