// Auto-generated by scripts/gpx-to-level.ts — do not edit manually
import type { LevelData } from '../types';
import course from './course.json';
import altitude from './altitude.json';
import water from './water.json';
import buildings from './buildings.json';
import paths from './paths.json';

const level: LevelData = {
  id: 'cheltenham',
  name: 'Cheltenham',
  course: course as LevelData['course'],
  altitude,
  water: water as LevelData['water'],
  buildings: buildings as LevelData['buildings'],
  paths: paths as LevelData['paths'],
};

export default level;
