// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types'
import course from './course'
import altitude from './altitude'
import water from './water'
import buildings from './buildings'
import paths from './paths'
import roads from './roads'
import objects from './objects'
import trees from './trees'
import regions from './regions'
import bridges from './bridges'

const level: LevelData = {
	id: 'cheltenham',
	name: 'Cheltenham',
	course,
	altitude,
	water,
	buildings,
	paths,
	roads,
	objects,
	manualTrees: trees,
	regions,
	bridges,
}

export default level
