// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types'
import altitude from './altitude'
import buildings from './buildings'
import course from './course'
import objects from './objects'
import paths from './paths'
import regions from './regions'
import roads from './roads'
import water from './water'

// Shift roads 50 m west and 15 m north (at ~59.35°N latitude)
const LAT_PER_METRE = 1 / 111_000
const LON_PER_METRE = 1 / (111_000 * Math.cos((59.35 * Math.PI) / 180))
const dLat = 10 * LAT_PER_METRE // 15 m north
const dLon = -40 * LON_PER_METRE // 50 m west
const shiftedRoads = roads?.map((road) =>
	road.map(([lat, lon]) => [lat + dLat, lon + dLon] as [number, number]),
)

const level: LevelData = {
	id: 'judarskogen',
	name: 'Judarskogen',
	course,
	altitude,
	water,
	buildings,
	paths,
	roads: shiftedRoads,
	objects,
	regions,
}

export default level
