// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types';
import course from './course.json';
import altitude from './altitude.json';
import water from './water.json';
import buildings from './buildings.json';
import paths from './paths.json';
import roads from './roads.json';
import objects from './objects.json';

// Shift roads 50 m west and 15 m north (at ~59.35°N latitude)
const LAT_PER_METRE = 1 / 111_000;
const LON_PER_METRE = 1 / (111_000 * Math.cos(59.35 * Math.PI / 180));
const dLat = 10 * LAT_PER_METRE;   // 15 m north
const dLon = -40 * LON_PER_METRE;  // 50 m west
const shiftedRoads = (roads as LevelData['roads'])!.map((road) =>
  road.map(([lat, lon]) => [lat + dLat, lon + dLon] as [number, number]),
);

const level: LevelData = {
  id: 'judarskogen',
  name: 'Judarskogen',
  course: course as LevelData['course'],
  altitude: altitude as LevelData['altitude'],
  water: water as LevelData['water'],
  buildings: buildings as LevelData['buildings'],
  paths: paths as LevelData['paths'],
  roads: shiftedRoads,
  objects: objects as LevelData['objects'],
};

export default level;
