// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types';
import course from './course.json';
import altitude from './altitude.json';
import water from './water.json';
import buildings from './buildings.json';
import paths from './paths.json';
import marshals from './marshals.json';

const level: LevelData = {
  id: 'haga',
  name: 'Haga',
  course: course as LevelData['course'],
  altitude,
  water: water as LevelData['water'],
  buildings: buildings as LevelData['buildings'],
  paths: paths as LevelData['paths'],
  marshals: marshals as LevelData['marshals'],
};

export default level;
