// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types'
import altCourse from './altCourse'
import altitude from './altitude'
import buildings from './buildings'
import course from './course'
import fences from './fences'
import marshals from './marshals'
import objects from './objects'
import paths from './paths'
import regions from './regions'
import roads from './roads'
import trees from './trees'
import water from './water'

const level: LevelData = {
	id: 'haga',
	name: 'Haga',
	course,
	altCourse,
	altitude,
	water,
	buildings,
	paths,
	marshals,
	roads,
	regions,
	manualTrees: trees,
	customFences: fences,
	objects,
}

export default level
