// Auto-generated by scripts/gpx-to-level.ts — do not edit manually
import type { LevelData } from '../types'
import altitude from './altitude'
import buildings from './buildings'
import course from './course'
import paths from './paths'
import roads from './roads'
import water from './water'

const level: LevelData = {
	id: 'uppsala',
	name: 'Uppsala',
	course,
	altitude,
	water,
	buildings,
	paths,
	roads,
}

export default level
