// Auto-generated by scripts/fetch-level.ts — do not edit manually
import type { LevelData } from '../types';
import course from './course.json';
import altitude from './altitude.json';
import water from './water.json';

const level: LevelData = {
  id: 'uppsala',
  name: 'Uppsala',
  course: course as LevelData['course'],
  altitude,
  water: water as LevelData['water'],
  hide: true,
};

export default level;
